#!/bin/bash
BUILDROOT_LATEST="buildroot-2023.08-rc1"
SUPPORTED_FORMATS=("av1" "avc" "webm" "efi")
SUPPORTED_STYLES=("disk" "ram" "hybrid")

#this script deploys configs generated by the vidos format patches
#if you have made a change to the vidos base config, run this script so it gets propegated :>)


for FORMAT in "$@"; do

 	patch configs/vidos_base_config patches/vidos_$FORMAT.patch -o "vidos_"$FORMAT"_config"
	cp "vidos_"$FORMAT"_config" $BUILDROOT_LATEST/$FORMAT/.config
	pushd $BUILDROOT_LATEST/
        make O=$FORMAT olddefconfig
	popd

done

